#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-nanoserver-1903 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-nanoserver-1903 AS build
WORKDIR /src
COPY ["src/Pokemon.Web.Mvc/Pokemon.Web.Mvc.csproj", "src/Pokemon.Web.Mvc/"]
COPY ["src/Pokemon.Application/Pokemon.Application.csproj", "src/Pokemon.Application/"]
COPY ["src/Pokemon.Application.Shared/Pokemon.Application.Shared.csproj", "src/Pokemon.Application.Shared/"]
COPY ["src/Pokemon.Core/Pokemon.Core.csproj", "src/Pokemon.Core/"]
COPY ["src/Pokemon.EntityFrameworkCore/Pokemon.EntityFrameworkCore.csproj", "src/Pokemon.EntityFrameworkCore/"]
RUN dotnet restore "src/Pokemon.Web.Mvc/Pokemon.Web.Mvc.csproj"
COPY . .
WORKDIR "/src/src/Pokemon.Web.Mvc"
RUN dotnet build "Pokemon.Web.Mvc.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Pokemon.Web.Mvc.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Pokemon.Web.Mvc.dll"]